import requests
import json


APIKEY = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhU1RaZm42bHpTdURYcUttRkg1SzN5UDFhT0FxUkhTNm9OendMUExaTXhFIn0.eyJleHAiOjE4MDgyOTc2MjcsImlhdCI6MTcxMzYwMzIyNywianRpIjoiNzYwYTFjZGItYTQ0Ni00YzAwLWEzYTUtMTMzNzk5MzRkNmQxIiwiaXNzIjoiaHR0cHM6Ly9rYy5wZXRlcnNidXJnLnJ1L3JlYWxtcy9lZ3MtYXBpIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjY1OGQzOTI1LTdlODAtNDk3NS05NzM5LTJiMTNhM2E0MzllZCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLXJlc3QtY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6IjI3ODY2MjBjLWQxODAtNGJhZi05NjFlLWM4M2Q2Y2JkMGU0NSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiLyoiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtZWdzLWFwaSIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiIyNzg2NjIwYy1kMTgwLTRiYWYtOTYxZS1jODNkNmNiZDBlNDUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJQYXNoY2hua28gQWxleGV5IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiYTJlYzczYWI5NTVhMzE2MTVkNjRhYjMyMzE1NzNiMmIiLCJnaXZlbl9uYW1lIjoiUGFzaGNobmtvIiwiZmFtaWx5X25hbWUiOiJBbGV4ZXkifQ.kLHcH1Dlajt9WmmeDZJu97CEwKrFH658cmXisjyIcMolPMPy74LsgJ-lq5cj3XhqrkSl54knqL9T2YyEHDtbn3aFUjNxUoLSzSeCLe0ZqLwCgIt9IYTFpPMl14yhZVCoHQgmZ5pExzqYCDtv4H1Ry9Bv-yv2vezx8-tRbGwLXqP228nAmWdrs7yaBQpNkW5LXy6a_wZKQxNZRDUYeFiyR4BaZvtjr9xYX6soO7lzgSC165ujq_d_Vto2zJ2NusYuCVFpBDnhL7qinfrIHcC6kX0HXzO43gN-3uRtlJh0SyiK-OvxaS-ZuRAMfHtXMHkk5Xy2f-2RFGHfbrszTTVvRA"
params = {"fields": "id,title,place,body_text,dates,price,favorites_count,site_url",
          "count": 15,
          "categories": "concert"}

url = "https://spb-afisha.gate.petersburg.ru/kg/external/afisha/events"
page = requests.get(url, params=params)
print(page.status_code)
print(page.text)
with open("result.json", "w", encoding="utf8") as file:
    file.write(page.text)
